"""unique email constraint

Revision ID: ea40abbd3e63
Revises: 74a9caf276da
Create Date: 2025-02-09 08:15:54.333995

"""

import sqlalchemy as sa
from alembic import op

import auth

# revision identifiers, used by Alembic.
revision = "ea40abbd3e63"
down_revision = "74a9caf276da"
branch_labels = None
depends_on = None


def upgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(f"{table_prefix}users_email_key", f"{table_prefix}users", type_="unique")
    op.drop_index(f"ix_{table_prefix}users_email", table_name=f"{table_prefix}users")
    op.create_index(op.f(f"ix_{table_prefix}users_email"), f"{table_prefix}users", ["email"], unique=True)
    op.drop_index(f"ix_{table_prefix}users_email_lower", table_name=f"{table_prefix}users")
    op.create_index(
        op.f(f"ix_{table_prefix}users_email_lower"), f"{table_prefix}users", ["email_lower"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f(f"ix_{table_prefix}users_email_lower"), table_name=f"{table_prefix}users")
    op.create_index(
        op.f(f"ix_{table_prefix}users_email_lower"), f"{table_prefix}users", ["email_lower"], unique=False
    )
    op.drop_index(op.f(f"ix_{table_prefix}users_email"), table_name=f"{table_prefix}users")
    op.create_index(op.f(f"ix_{table_prefix}users_email"), f"{table_prefix}users", ["email"], unique=False)
    op.create_unique_constraint(f"{table_prefix}users_email_key", f"{table_prefix}users", ["email"])
    # ### end Alembic commands ###
