"""tenants_default_roles

Revision ID: 0dc105233539
Revises: a736fe95ec4f
Create Date: 2025-02-08 18:28:28.654217

"""

import sqlalchemy as sa
from alembic import op

import auth

# revision identifiers, used by Alembic.
revision = "0dc105233539"
down_revision = "a736fe95ec4f"
branch_labels = None
depends_on = None


def upgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        f"{table_prefix}tenants_default_roles",
        sa.Column("tenant_id", auth.models.generics.GUID(), nullable=False),
        sa.Column("role_id", auth.models.generics.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            [f"{table_prefix}roles.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            [f"{table_prefix}tenants.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(f"{table_prefix}tenants_default_roles")
    # ### end Alembic commands ###
