"""remove user unique tenant constraint

Revision ID: 74a9caf276da
Revises: 0dc105233539
Create Date: 2025-02-09 06:40:58.913091

"""

import sqlalchemy as sa
from alembic import op

import auth

# revision identifiers, used by Alembic.
revision = "74a9caf276da"
down_revision = "0dc105233539"
branch_labels = None
depends_on = None


def upgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(f"{table_prefix}users_email_tenant_id_key", f"{table_prefix}users", type_="unique")
    op.create_unique_constraint(op.f(f"{table_prefix}users_email_key"), f"{table_prefix}users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f(f"{table_prefix}users_email_key"), f"{table_prefix}users", type_="unique")
    op.create_unique_constraint(
        f"{table_prefix}users_email_tenant_id_key", f"{table_prefix}users", ["email", "tenant_id"]
    )
    # ### end Alembic commands ###
