"""organization_invitation_client

Revision ID: 78dd8ccb7398
Revises: c3162a996581
Create Date: 2025-03-02 02:14:30.902785

"""

import sqlalchemy as sa
from alembic import op

import auth

# revision identifiers, used by Alembic.
revision = "78dd8ccb7398"
down_revision = "c3162a996581"
branch_labels = None
depends_on = None


def upgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        f"{table_prefix}organization_invitations",
        sa.Column("client_id", auth.models.generics.GUID(), nullable=False),
    )
    op.add_column(
        f"{table_prefix}organization_invitations",
        sa.Column(
            "redirect_uri",
            sa.String(length=512),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f(
            f"fk_{table_prefix}organization_invitations_client_id_{table_prefix}clients"
        ),
        f"{table_prefix}organization_invitations",
        f"{table_prefix}clients",
        ["client_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f(
            f"fk_{table_prefix}organization_invitations_client_id_{table_prefix}clients"
        ),
        f"{table_prefix}organization_invitations",
        type_="foreignkey",
    )
    op.drop_column(f"{table_prefix}organization_invitations", "redirect_uri")
    op.drop_column(f"{table_prefix}organization_invitations", "client_id")
    # ### end Alembic commands ###
