"""organization_migrations

Revision ID: 407008d4e7f5
Revises: ea40abbd3e63
Create Date: 2025-02-22 03:24:23.347279

"""

import sqlalchemy as sa
from alembic import op

import auth

# revision identifiers, used by Alembic.
revision = "407008d4e7f5"
down_revision = "ea40abbd3e63"
branch_labels = None
depends_on = None


def upgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        f"{table_prefix}organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", auth.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            auth.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            auth.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f(f"pk_{table_prefix}organizations")),
    )
    op.create_index(
        op.f(f"ix_{table_prefix}organizations_created_at"),
        f"{table_prefix}organizations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f(f"ix_{table_prefix}organizations_updated_at"),
        f"{table_prefix}organizations",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f(f"ix_{table_prefix}organizations_updated_at"),
        table_name=f"{table_prefix}organizations",
    )
    op.drop_index(
        op.f(f"ix_{table_prefix}organizations_created_at"),
        table_name=f"{table_prefix}organizations",
    )
    op.drop_table(f"{table_prefix}organizations")
    # ### end Alembic commands ###
