"""unique email constraint

Revision ID: ea40abbd3e63
Revises: 74a9caf276da
Create Date: 2025-02-09 08:15:54.333995

"""

import sqlalchemy as sa
from alembic import op

import auth

# revision identifiers, used by Alembic.
revision = "ea40abbd3e63"
down_revision = "74a9caf276da"
branch_labels = None
depends_on = None


def upgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("auth_users_email_key", "auth_users", type_="unique")
    op.drop_index("ix_auth_users_email", table_name="auth_users")
    op.create_index(op.f("ix_auth_users_email"), "auth_users", ["email"], unique=True)
    op.drop_index("ix_auth_users_email_lower", table_name="auth_users")
    op.create_index(
        op.f("ix_auth_users_email_lower"), "auth_users", ["email_lower"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    table_prefix = op.get_context().opts["table_prefix"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_users_email_lower"), table_name="auth_users")
    op.create_index(
        "ix_auth_users_email_lower", "auth_users", ["email_lower"], unique=False
    )
    op.drop_index(op.f("ix_auth_users_email"), table_name="auth_users")
    op.create_index("ix_auth_users_email", "auth_users", ["email"], unique=False)
    op.create_unique_constraint("auth_users_email_key", "auth_users", ["email"])
    # ### end Alembic commands ###
