# Organization role
ORGANIZATION_ROLE_NAME = "Organization"

# Organization permissions
ORGANIZATION_UPDATE_NAME = "Update Organization"
ORGANIZATION_UPDATE_CODENAME = "org:update"

ORGANIZATION_DELETE_NAME = "Delete Organization"
ORGANIZATION_DELETE_CODENAME = "org:delete"

ORGANIZATION_MEMBER_LIST_NAME = "List Members"
ORGANIZATION_MEMBER_LIST_CODENAME = "org:member:list"

ORGANIZATION_MEMBER_REMOVE_NAME = "Remove Member"
ORGANIZATION_MEMBER_REMOVE_CODENAME = "org:member:remove"

ORGANIZATION_MEMBER_PERMISSION_ADD_NAME = "Add Member Permission"
ORGANIZATION_MEMBER_PERMISSION_ADD_CODENAME = "org:member:permission:add"

ORGANIZATION_MEMBER_PERMISSION_REMOVE_NAME = "Remove Member Permission"
ORGANIZATION_MEMBER_PERMISSION_REMOVE_CODENAME = "org:member:permission:remove"


ORGANIZATION_INVITE_NAME = "Invite Member"
ORGANIZATION_INVITE_CODENAME = "org:invite"

ORGANIZATION_INVITE_REVOKE_NAME = "Revoke Invitation"
ORGANIZATION_INVITE_REVOKE_CODENAME = "org:invite:revoke"

ORGANIZATION_INVITE_RESEND_NAME = "Resend Invitation"
ORGANIZATION_INVITE_RESEND_CODENAME = "org:invite:resend"

ORGANIZATION_INVITE_LIST_NAME = "List Invitations"
ORGANIZATION_INVITE_LIST_CODENAME = "org:invite:list"

ORGANIZATION_PERMISSIONS = {
    ORGANIZATION_UPDATE_NAME: ORGANIZATION_UPDATE_CODENAME,
    ORGANIZATION_DELETE_NAME: ORGANIZATION_DELETE_CODENAME,
    ORGANIZATION_MEMBER_LIST_NAME: ORGANIZATION_MEMBER_LIST_CODENAME,
    ORGANIZATION_MEMBER_REMOVE_NAME: ORGANIZATION_MEMBER_REMOVE_CODENAME,
    ORGANIZATION_MEMBER_PERMISSION_ADD_NAME: ORGANIZATION_MEMBER_PERMISSION_ADD_CODENAME,
    ORGANIZATION_MEMBER_PERMISSION_REMOVE_NAME: ORGANIZATION_MEMBER_PERMISSION_REMOVE_CODENAME,
    ORGANIZATION_INVITE_NAME: ORGANIZATION_INVITE_CODENAME,
    ORGANIZATION_INVITE_REVOKE_NAME: ORGANIZATION_INVITE_REVOKE_CODENAME,
    ORGANIZATION_INVITE_RESEND_NAME: ORGANIZATION_INVITE_RESEND_CODENAME,
    ORGANIZATION_INVITE_LIST_NAME: ORGANIZATION_INVITE_LIST_CODENAME,
}
